# WorldwideChat Configuration
#       _    _            _     _          _     _      _____ _           _   
#      | |  | |          | |   | |        (_)   | |    /  __ \ |         | |  
#      | |  | | ___  _ __| | __| |_      ___  __| | ___| /  \/ |__   __ _| |_ 
#      | |/\| |/ _ \| '__| |/ _` \ \ /\ / / |/ _` |/ _ \ |   | '_ \ / _` | __|    - by 3xpl0itz
#      \  /\  / (_) | |  | | (_| |\ V  V /| | (_| |  __/ \__/\ | | | (_| | |_ 
#       \/  \/ \___/|_|  |_|\__,_| \_/\_/ |_|\__,_|\___|\____/_| |_|\__,_|\__|

General:
  
  # Change the prefix that appears next to messages sent by this plugin.
  # Default is "Default" to use the built-in prefix.
  prefixName: Default
  
  # Enable or disable bStats.
  # Default is "true" for enable.
  # Change this value to "false" to disable bStats :(.
  enablebStats: true
  
  # Change plugin language.
  # Default is "en" for English.
  # Currently supported languages: en
  pluginLang: en
  
  # The delay between each check for updates from the plugin's github repo.
  # Must be a minimum of 10 seconds so that you don't kill your server with update requests.
  # Default is 86400 (seconds), or 1 day.
  updateCheckerDelay: 86400
  
Translator:

  # Please Note: YOU CAN ONLY HAVE ONE TRANSLATOR ENABLED AT A TIME.

  # Watson Configuration: Change to true to enable, and fill out the required information below.
  # Because Watson has the best free plan, it is used by default.
  # Set to "false" to not use it.
  # The default is true.
  useWatsonTranslate: true
  watsonAPIKey: 
  watsonURL:
  
  # Coming Soon: Google Translate API support :) Ignore the text below for now.
  # Watson Configuration: Change to true to enable, and fill out the required information below.
  # Has a more restrictive "free" plan compared to Watson, but may be more accurate.
  # useGoogleTranslate is default "false," meaning it is not used. Set to "true" to use it, but make sure Watson is false.
  useGoogleTranslate: false
  
  # Set the number of phrases to be stored in the "translation cache."
  # This cache will store your X most translated phrases. This might be faster if:
  # Your ping times to a translation server are trash OR you have a fast machine with plenty of resources + RAM.
  # Set to 0 to disable this feature, in case you think it is negatively affecting your performance.
  # I would not recommend setting this above a couple hundred, especially if you have less performant hardware.
  # The default is 10.
  translatorCacheSize: 10
  
  # The End! For now...:)