name: WorldwideChat
version: 1.15
description: Break the blocky language barrier!
api-version: 1.14
author: 3xpl0itz
softdepend: [DeluxeChat]
main: com.expl0itz.worldwidechat.WorldwideChat
commands:
    wwc:
        description: Prints WorldwideChat version.
        aliases: [worldwidechat]
        usage: §4/wwc
        permission: worldwidechat.wwc
        permission-message: §4You do not have permission to run this command.
    wwcr:
        description: Reloads WorldwideChat.
        aliases: [wwcreload, translatereload]
        usage: §4/wwcr
        permission: worldwidechat.wwcr
        permission-message: §4You do not have permission to run this command.
    wwcg:
        description: Enables chat translation to another language globally.
        aliases: [wwcglobal, gtranslate]
        usage: §4/wwcg (language-in) <language-out>
        permission: worldwidechat.wwcg
        permission-message: §4You do not have permission to run this command.
    wwct:
        description: Enables chat translation to a certain language, either for you or a specific player.
        aliases: [wwctranslate, translate]
        usage: §4/wwct (playerName) (language-in) <language-out>
        permission: worldwidechat.wwct
        permission-message: §4You do not have permission to run this command.
    wwctb:
        description: Enables book translation to a certain language.
        aliases: [wwctranslatebook, translatebook]
        usage: §4/wwctb (playerName)
        permission: worldwidechat.wwctb
        permission-message: §4You do not have permission to run this command.
    wwcts:
        description: Enables sign translation to a certain language.
        aliases: [wwctranslatesign, translatesign]
        usage: §4/wwcts (playerName)
        permission: worldwidechat.wwcts
        permission-message: §4You do not have permission to run this command.
    wwcs:
        description: Gets translation stats for a specified user.
        aliases: [wwctranslatestats, translatestats]
        usage: §4/wwcs <playerName>
        permission: worldwidechat.wwcs
        permission-message: §4You do not have permission to run this command.
permissions:
    worldwidechat.*:
        description: Gives access to all WorldwideChat commands.
        children:
            worldwidechat.wwc: true
            worldwidechat.wwcr: true
            worldwidechat.wwcg: true
            worldwidechat.wwct: true
            worldwidechat.wwct.otherplayers: true
            worldwidechat.chatupdate: true
            worldwidechat.wwctb: true
            worldwidechat.wwctb.otherplayers: true
            worldwidechat.wwcts: true
            worldwidechat.wwcts.otherplayers: true
            worldwidechat.wwcs: true
        default: op
    worldwidechat.wwc:
        description: Prints WorldwideChat version.
        default: true
    worldwidechat.wwcr:
        description: Reloads WorldwideChat.
        default: op
    worldwidechat.wwcg:
        description: Enables chat translation to a particular language globally.
        default: op
    worldwidechat.wwct:
        description: Enables chat translation to a certain language for a specific player.
        default: true
    worldwidechat.wwct.otherplayers:
        description: Enables chat translation to a certain language for other players.
        default: op
    worldwidechat.chatupdate:
        description: Enables receiving of plugin update notification in chat on login.
        default: op
    worldwidechat.wwctb:
        description: Enables book translation to a certain language.
        default: true
    worldwidechat.wwctb.otherplayers:
        description: Enables book translation to a certain language on target players.
        default: op
    worldwidechat.wwcts:
        description: Enables sign translation to a certain language.
        default: true
    worldwidechat.wwcts.otherplayers:
        description: Enables sign translation to a certain language on target players.
        default: op
    worldwidechat.wwcs:
        description: Gets translation stats for a specified user.
        default: op
    
    
