name: WorldwideChat
version: 1.01
description: Translate incoming chat to any language!
api-version: 1.16
author: 3xpl0itz
main: com.expl0itz.worldwidechat.WorldwideChat
commands:
    wwc:
        description: Prints WorldwideChat version.
        aliases: [worldwidechat]
        usage: §4/wwc
        permission: worldwidechat.wwc
        permission-message: §4You do not have permission to run this command.
    wwcr:
        description: Reloads WorldwideChat.
        aliases: [worldwidechatreload]
        usage: §4/wwcr
        permission: worldwidechat.wwcr
        permission-message: §4You do not have permission to run this command.
    wwcg:
        description: Enables chat translation to another language globally.
        aliases: [worldwidechatglobal, gtranslate]
        usage: §4/wwcg (language-in) <language-out>
        permission: worldwidechat.wwcg
        permission-message: §4You do not have permission to run this command.
    wwct:
        description: Enables chat translation to a certain language, either for you or a specific player.
        aliases: [worldwidechattranslate, translate]
        usage: §4/wwct (playerName) (language-in) <language-out>
        permission: worldwidechat.wwct
        permission-message: §4You do not have permission to run this command.
permissions:
    worldwidechat.*:
        description: Gives access to all WorldwideChat commands.
        children:
            worldwidechat.wwc: true
            worldwidechat.wwcr: true
            worldwidechat.wwcg: true
            worldwidechat.wwct: true
            worldwidechat.wwctotherplayers: true
            worldwidechat.chatupdate: true
        default: op
    worldwidechat.wwc:
        description: Prints WorldwideChat version.
        default: true
    worldwidechat.wwcr:
        description: Reloads WorldwideChat.
        default: op
    worldwidechat.wwcg:
        description: Enables chat translation to a particular language globally.
        default: op
    worldwidechat.wwct:
        description: Enables chat translation to a certain language for a specific player.
        default: true
    worldwidechat.wwctotherplayers:
        description: Enables chat translation to a certain language for other players.
        default: op
    worldwidechat.chatupdate:
        description: Enables receiving of plugin update notification in chat on login.
        default: op
    
